// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class enlemboylamguncellendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enlemboylamguncellendi));
        
        string IMigrationMetadata.Id
        {
            get { return "202411290921140_enlemboylamguncellendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
