// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class etkinlikmesaj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(etkinlikmesaj));
        
        string IMigrationMetadata.Id
        {
            get { return "202411291314553_etkinlikmesaj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
